### ISSUE TITLE
No results 

### ISSUE THREAD

**Issue by alfasst** [ivankliuk/duckduckpy#4]
I tried this code:

```
from duckduckpy import query
response = query('python')
print(response.results)
```
All I get is an empty list.

**Comment by ivankliuk** [comment]
@alfasst please specify Python version.

**Comment by franz101** [comment]
Same here tried it on Google Colab

**Comment by alfasst** [comment]
@ivankliuk 
Python 3.7.5 on Fedora 29

**Comment by Ahthe45th** [comment]
I too have had this same problem
Got the following as I printed the response
`Response(answer='', abstract='', redirect='', heading='', results=[], infobox='', image_width='', type='', image_height='', abstract_source='', definition_source='', image='', answer_type='', abstract_text='', definition='', meta=None, entity='', abstract_url='', image_is_logo='', definition_url='', related_topics=[])
Traceback (most recent call last):
  File "capabilities/research/gatherinfo.py", line 28, in <module>
    do_research('question', 'Whats the meaning of life', None, None)
  File "capabilities/research/gatherinfo.py", line 16, in do_research
    response = response['related_topics']
TypeError: tuple indices must be integers or slices, not str
`

**Comment by alfasst** [comment]
This happens often with DuckDuckGo. So not associated with duckduckpy.
